/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab3_filemanagerwithimageseditor;

import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luk
 */
public class GuiApp extends javax.swing.JFrame {

    FoldersList foldersList;
    ArrayList<String> imagesPaths;
    ArrayList<ImageIcon> imagesIcons;

    /**
     * Creates new form guiApp
     */
    public GuiApp() {

        initComponents();
        foldersList = new FoldersList();
        foldersList.add(new Folder(0, "G:\\Lukasz\\Desktop\\PWR\\semestr_6\\java\\netbans\\lab3_FileManagerWithImagesEditor\\folders\\cats", "Koty"));
        foldersList.add(new Folder(1, "G:\\Lukasz\\Desktop\\PWR\\semestr_6\\java\\netbans\\lab3_FileManagerWithImagesEditor\\folders\\dogs", "Psy"));
        foldersComboBox.removeAllItems();
        for (int i = 0; i < foldersList.getFoldersList().size(); i++) {
            foldersComboBox.addItem(foldersList.getFoldersList().get(i).getItem());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        doModButton = new javax.swing.JButton();
        modesComboBox = new javax.swing.JComboBox<>();
        foldersComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        picturesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        jLabel1.setText("Miniatura:");

        doModButton.setText("Zastosuj");
        doModButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doModButtonActionPerformed(evt);
            }
        });

        modesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        foldersComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foldersComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Wybierz folder:");

        jScrollPane1.setViewportView(picturesTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(foldersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modesComboBox, 0, 70, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(doModButton)
                        .addGap(129, 129, 129))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(foldersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doModButton)
                            .addComponent(modesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doModButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doModButtonActionPerformed
        initTable();
    }//GEN-LAST:event_doModButtonActionPerformed

    private void foldersComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foldersComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foldersComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GuiApp().setVisible(true);
        });
    }

    private void initTable() {

        String path = foldersList.getItem(foldersComboBox.getSelectedIndex()).getPath();
        File currFolder = new File(path);
        Icon one = null, two = null, three = null, four = null, five = null;
        imagesPaths = new ArrayList(Arrays.asList(currFolder.list()));
        imagesIcons = new ArrayList();
        if (foldersComboBox.getSelectedIndex() == 0) {
            one = new ImageIcon("G:\\Lukasz\\Desktop\\PWR\\semestr_6\\java\\netbans\\lab3_FileManagerWithImagesEditor\\folders\\cats\\kot1.jpg");
            two = new ImageIcon("G:\\Lukasz\\Desktop\\PWR\\semestr_6\\java\\netbans\\lab3_FileManagerWithImagesEditor\\folders\\cats\\kot2.jpg");
            three = new ImageIcon("G:\\Lukasz\\Desktop\\PWR\\semestr_6\\java\\netbans\\lab3_FileManagerWithImagesEditor\\folders\\cats\\kot3.jpg");
            four = new ImageIcon("G:\\Lukasz\\Desktop\\PWR\\semestr_6\\java\\netbans\\lab3_FileManagerWithImagesEditor\\folders\\cats\\kot4.jpg");
            five = new ImageIcon("G:\\Lukasz\\Desktop\\PWR\\semestr_6\\java\\netbans\\lab3_FileManagerWithImagesEditor\\folders\\cats\\kot5.jpg");

        } else if (foldersComboBox.getSelectedIndex() == 1) {
            one = new ImageIcon("G:\\Lukasz\\Desktop\\PWR\\semestr_6\\java\\netbans\\lab3_FileManagerWithImagesEditor\\folders\\dogs\\pies1.jpg");
            two = new ImageIcon("G:\\Lukasz\\Desktop\\PWR\\semestr_6\\java\\netbans\\lab3_FileManagerWithImagesEditor\\folders\\dogs\\pies2.jpg");
            three = new ImageIcon("G:\\Lukasz\\Desktop\\PWR\\semestr_6\\java\\netbans\\lab3_FileManagerWithImagesEditor\\folders\\dogs\\pies3.jpg");
            four = new ImageIcon("G:\\Lukasz\\Desktop\\PWR\\semestr_6\\java\\netbans\\lab3_FileManagerWithImagesEditor\\folders\\dogs\\pies4.jpg");
            five = new ImageIcon("G:\\Lukasz\\Desktop\\PWR\\semestr_6\\java\\netbans\\lab3_FileManagerWithImagesEditor\\folders\\dogs\\pies5.jpg");

        }
        String[] columnNames = {"Picture", "Picture"};
        Object[][] data
                = {
                    {one, two},
                    {three, four},
                    {five,}};
        DefaultTableModel model = new DefaultTableModel(data, columnNames) {
            //  Returning the Class of each column will allow different
            //  renderers to be used based on Class
            @Override
            public Class getColumnClass(int column) {
                return getValueAt(0, column).getClass();
            }
        };
        
        picturesTable.setRowHeight(200);
        picturesTable.setModel(model);
        picturesTable.setPreferredScrollableViewportSize(picturesTable.getPreferredSize());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doModButton;
    private javax.swing.JComboBox<String> foldersComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> modesComboBox;
    private javax.swing.JTable picturesTable;
    // End of variables declaration//GEN-END:variables
}
